# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Probability mass function of the three-parameter EWP
#'
#' @param x vector of (positive integer) quantiles.
#' @param lambda centrality parameter
#' @param beta1 lower-tail dispersion parameter
#' @param beta2 upper tail dispersion parameter
#'
#' @return a probability mass
#' @export
dewp3_cpp <- function(x, lambda, beta1, beta2) {
    .Call(`_ewp_dewp3_cpp`, x, lambda, beta1, beta2)
}

pllik3_part_cpp <- function(X, lambda, beta1, beta2) {
    .Call(`_ewp_pllik3_part_cpp`, X, lambda, beta1, beta2)
}

